### ISSUE TITLE
The data format is correct?

### ISSUE THREAD

**Issue by hbzhang** [periakiva/finding_berries#2]
There, we found there is discrepancy between the YAML file versus the provided data,.

In YAML file, the data configure is like this:

data:
  image_size: 456x608
  local:
    type: semantic_seg
    model_save_dir: /home/native/projects/data/cranberry/models/
    train_dir: /home/native/projects/data/cranberry/points/instance_points/
    test_dir: /home/native/projects/data/cranberry/semantic_seg/
    val_dir:
  docker:
    type: semantic_seg
    model_save_dir: /app/finding_berries/models/
    train_dir: /app/finding_berries/data/instance_points/
    test_dir: /app/finding_berries/data/semantic_seg/
    val_dir:

Yet, the downloaded data folder structure,  we have not found the instance_points folder at all.  Please provide insight.

![image](https://user-images.githubusercontent.com/205781/134248137-f62c0e9b-9c89-4a68-8c33-f3f58f7f385f.png)

**Comment by periakiva** [comment]
There might be a few path inconsistensies. We are rolling out new data which takes on a different directory structure, which as you pointed out, does not match our old code. We plan on updating the code soon to work out-of-the-box, but feel free to make any necessary changes to make it work on your machine.

**Comment by hbzhang** [comment]
Thanks. But the images in the perturbedpoints and pointsclass  (within
train folder) are just empty images.

Are they correct images? What these empty images are used for?

I can find the images folder (supposed to be the raw images). But where I
can find the labels?

[image: image.png]

**Comment by periakiva** [comment]
They are not empty. They may seem all-black since they are saved as .png (0-255 pixel values), but there are 0's and 1's representing background and berry centers. If you load an image and run np.unique(), there will be 1 labeled pixels.

**Comment by hbzhang** [comment]
What are the differences between perturbed points and pointsclass?

I do not see anywhere in the code that is used. How do they suppose to be
used in the training pipeline?

If you have updated code. Do you mind uploading it as a branch (I
understand it may not be stable for formal release).

Thanks!

**Comment by periakiva** [comment]
The PerturbedPoints masks directory is an extension we used in a different paper with un-released code as of today. It will be released in the near future. 

I will update this repository with a link to the new code when it is released.

**Comment by hbzhang** [comment]
Do you mind sharing the actual data working for this code? Thanks!

**Comment by periakiva** [comment]
I just tested the current code and it works with the data. You need to point the data directory in the training or evaluation yaml file to the correct location (either PointClass for points, or SegmentationClass for evaluation). 

Let me know if it works out.

**Comment by hbzhang** [comment]
Will test them out and keep you posted. Thanks again.
